# Generated by Django 2.1.1 on 2018-12-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(choices=[(0, 'badge-comment.png'), (1, 'badge-reply.png'), (2, 'badge-change.png'), (3, 'badge-desire.png'), (4, 'badge-SocialMedia.png')], max_length=100)),
                ('type', models.CharField(choices=[(0, 'Fez um comentário'), (1, 'Recomendou uma mudança'), (2, 'Escreveu um desejo'), (3, 'Compartilhou nas redes sociais'), (4, 'Respondeu à um comentário')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conquests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Assista Isso!'), (1, 'Trouxe alguém'), (2, 'Respondeu à pesquisa'), (3, 'Fez um elogio'), (4, 'Reclamação'), (5, 'Postagem')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(choices=[(0, 'medal-comentador.png'), (1, 'medal-response.png'), (2, 'medal-valor.png')], max_length=100)),
                ('type', models.CharField(choices=[(0, 'Comentador'), (1, 'Resposta'), (2, 'Valoroso')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_allowed_to_post', models.BooleanField(blank=True, default=False)),
                ('is_activated', models.BooleanField(blank=True, default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('badges', models.ManyToManyField(blank=True, default=None, to='users.Badges')),
                ('conquests', models.ManyToManyField(blank=True, default=None, to='users.Conquests')),
                ('medals', models.ManyToManyField(blank=True, default=None, to='users.Medals')),
            ],
        ),
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Astúcia'), (1, 'Audácia'), (2, 'Perseverança')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='shields',
            field=models.ManyToManyField(blank=True, default=None, to='users.Shields'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
