# Generated by Django 2.1.1 on 2018-12-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', tinymce.models.HTMLField(verbose_name='Content')),
                ('email_title', models.CharField(max_length=100)),
                ('email_to', models.CharField(choices=[('0', 'Usuários Ativos'), ('1', 'Usuários Inativos'), ('2', 'Usuários Permitidos Postar'), ('3', 'Usuários Não permitidos postar'), ('4', 'Todos')], default=4, max_length=100)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('emails', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
