# Generated by Django 2.1.1 on 2018-12-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'Arduino'), ('1', 'Raspberry pi'), ('2', 'Programação'), ('3', 'Como fazer'), ('4', 'Reuzo'), ('5', 'O que comprar com R$50,00'), ('6', 'O que comprar com R$200,00'), ('7', 'O que comprar com R$300,00'), ('8', 'Miscelanea')], default='Miscelanea', max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
